name: Build Release APK

on:
  push:
    tags:
      - "*"

jobs:
  build_and_publish_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      
      - run: flutter pub get
      # - run: flutter test
      - run: flutter build apk --release
      
      - name: Create Release
        uses: actions/upload-artifact@v4.2.0
        with:
          name: ${{github.ref_name}}
          path: build/app/outputs/apk/release/cramming_poems_${{github.ref_name}}.apk

